# Generated by Django 3.0.7 on 2020-06-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0004_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(max_length=100000)),
            ],
        ),
    ]
