# Generated by Django 3.0.7 on 2020-06-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0005_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='payload',
            field=models.CharField(max_length=1000000),
        ),
    ]
